Introducing search count feature
badasswp/search-and-replace pull request #19
Opened 2024-11-28 13:29 UTC by anandraj346

Previously on writing into the search input text, we were not shown how many matches found for that string. Introducing the search count feature will help user address how many counts of the search string found.

2024-11-28 21:12 UTC, badasswp requested changes
@anandraj346 I can see duplicity of effort & code in trying to implement this search count feature in this PR.

Since we already have those functions implemented, what we should be doing is passing in a `context` param that represents either a `true` (**replace**) state or `false` (**search**) state and then use that conditional in our `replaceBlockAttribute` callback.

Let's pass in the `context` param here:
```js
  const replace = (context = false): void => {
    setContext(context);
    setReplacements(0);
```

On this line, pass `context` in:
```js
    select('core/block-editor').getBlocks().forEach((element) => {
      recursivelyReplace(element, pattern, replaceInput, context);
    });
```

Do the same for other functions until we get to the `replaceBlockAttribute` callback. In this method, let's check for the context value and if it is TRUE, then let's replace.
```js
    if (context) {
      (dispatch('core/block-editor') as any).updateBlockAttributes(clientId, property);
    }
```

Same here:
```js
    // Handle edge-case ('value') with Pullquotes.
    if (attributes.value) {
      if (context) {
        (dispatch('core/block-editor') as any)
          .updateBlockAttributes(clientId, { value: newString });
      }
      setReplacements((items) => items + 1);
    }
```

2024-11-28 21:23 UTC, badasswp commented
@anandraj346 Could you pls create an issue for this as well. Thanks.

2024-11-28 21:28 UTC, badasswp commented on src/app.tsx
>                  variant="primary"
@anandraj346 Let's refactor the `onClick` logic to this:

```js
                onClick={() => replace(true)}
```

2024-12-06 16:00 UTC, badasswp commented on src/core/app.tsx
> +              context ? (
@anandraj346 I see duplication here, let's refactor this to:

```js
            {
              replacements ? (
                <div id="search-replace-modal__notification">
                  <p>
                    {context ? (
                      <>
                        <strong>{replacements}</strong> {__('item(s) replaced successfully', 'search-replace-for-block-editor')}.
                      </>
                    ) : (
                      <>
                        <strong>{replacements}</strong> {__('item(s) found', 'search-replace-for-block-editor')}.
                      </>
                    )}
                  </p>
                </div>
              ) : ''
            }
```

2024-12-06 16:00 UTC, badasswp commented on src/core/app.tsx
> +            {
@anandraj346 Pls remove this.

2024-12-10 12:26 UTC, anandraj346 commented on src/core/app.tsx
> +            {
Resolved

2024-12-12 17:02 UTC, badasswp approved these changes
@anandraj346 This looks good 👍. Thanks for all your work on this.

<img width="399" alt="feature-search-count" src="https://github.com/user-attachments/assets/3fbe45d9-9a40-4f64-ac9f-7d39f7724904" />

2024-12-12 17:03 UTC, merged